### ISSUE TITLE
where is model?

### ISSUE THREAD

**Issue by benpaodewoniu** [mxkrn/onnxruntime-web-tutorial#1]
Where is alertNet onnx modex?

**Comment by konstantin-frolov** [comment]
You need run /src/onnx_model.py for creating model  *. onnx file

**Comment by mxkrn** [comment]
Expanding on @konstantin-frolov, the steps are:
1. Be in a python (virtual)env
2. `pip install torch torchvision`
3. `python src/onnx_model.py`
4. Model will be written to `assets/model.onnx`
