### ISSUE TITLE
Normalize image in preprocess

### ISSUE THREAD

**Issue by arunpatala** [mxkrn/onnxruntime-web-tutorial#3]
Hi,

Thanks for a great tutorial. It really helped me.

I just noticed that the image being processed (imageDataToTensor)
is not being normalized to be having mean zero.

Can you please confirm or is it not necessary?

Thanks

**Comment by arunpatala** [comment]
for (i = 0; i < l; i++) {
		float32Data[i] = transposedData[i] / MAX_SIGNED_VALUE; // convert to float
	}
	
	const mean = [0.485, 0.456, 0.406]
	const std = [0.229, 0.224, 0.225]
	
	for(let j=0;j<3;j++){
		let k = MAX_LENGTH_CHANNEL * j
		for (let i = 0; i < MAX_LENGTH_CHANNEL; i++) {				
			float32Data[i+k] = (float32Data[i+k]-mean[j])/std[j]
		}
		// here we skip data[i + 3] because it's the alpha channel
	}

**Comment by mxkrn** [comment]
Glad to hear it was useful!

You're right, I didn't implement any normalization. This example mainly exists to present how one would do this rather than trying to achieve good results.

**Comment by arunpatala** [comment]
closing then.
